using System;
using System.Runtime.InteropServices;
using System.Threading;

namespace TwitchPlaysController;

public static class KeyCodes
{
    public const ushort Q = 0x10;
    public const ushort W = 0x11;
    public const ushort E = 0x12;
    public const ushort R = 0x13;
    public const ushort T = 0x14;
    public const ushort Y = 0x15;
    public const ushort U = 0x16;
    public const ushort I = 0x17;
    public const ushort O = 0x18;
    public const ushort P = 0x19;
    public const ushort A = 0x1E;
    public const ushort S = 0x1F;
    public const ushort D = 0x20;
    public const ushort F = 0x21;
    public const ushort G = 0x22;
    public const ushort H = 0x23;
    public const ushort J = 0x24;
    public const ushort K = 0x25;
    public const ushort L = 0x26;
    public const ushort Z = 0x2C;
    public const ushort X = 0x2D;
    public const ushort C = 0x2E;
    public const ushort V = 0x2F;
    public const ushort B = 0x30;
    public const ushort N = 0x31;
    public const ushort M = 0x32;

    public const ushort LEFT_ARROW = 0xCB;
    public const ushort RIGHT_ARROW = 0xCD;
    public const ushort UP_ARROW = 0xC8;
    public const ushort DOWN_ARROW = 0xD0;
    public const ushort ESC = 0x01;
    public const ushort ONE = 0x02;
    public const ushort TWO = 0x03;
    public const ushort THREE = 0x04;
    public const ushort FOUR = 0x05;
    public const ushort FIVE = 0x06;
    public const ushort SIX = 0x07;
    public const ushort SEVEN = 0x08;
    public const ushort EIGHT = 0x09;
    public const ushort NINE = 0x0A;
    public const ushort ZERO = 0x0B;
    public const ushort MINUS = 0x0C;
    public const ushort EQUALS = 0x0D;
    public const ushort BACKSPACE = 0x0E;
    public const ushort APOSTROPHE = 0x28;
    public const ushort SEMICOLON = 0x27;
    public const ushort TAB = 0x0F;
    public const ushort CAPSLOCK = 0x3A;
    public const ushort ENTER = 0x1C;
    public const ushort LEFT_CONTROL = 0x1D;
    public const ushort LEFT_ALT = 0x38;
    public const ushort LEFT_SHIFT = 0x2A;
    public const ushort RIGHT_SHIFT = 0x36;
    public const ushort TILDE = 0x29;
    public const ushort PRINTSCREEN = 0x37;
    public const ushort NUM_LOCK = 0x45;
    public const ushort SPACE = 0x39;
    public const ushort DELETE = 0x53;
    public const ushort COMMA = 0x33;
    public const ushort PERIOD = 0x34;
    public const ushort BACKSLASH = 0x35;
    public const ushort FORWARDSLASH = 0x2B;
    public const ushort LEFT_BRACKET = 0x1A;
    public const ushort RIGHT_BRACKET = 0x1B;

    public const ushort F1 = 0x3B;
    public const ushort F2 = 0x3C;
    public const ushort F3 = 0x3D;
    public const ushort F4 = 0x3E;
    public const ushort F5 = 0x3F;
    public const ushort F6 = 0x40;
    public const ushort F7 = 0x41;
    public const ushort F8 = 0x42;
    public const ushort F9 = 0x43;
    public const ushort F10 = 0x44;
    public const ushort F11 = 0x57;
    public const ushort F12 = 0x58;

    public const ushort NUMPAD_0 = 0x52;
    public const ushort NUMPAD_1 = 0x4F;
    public const ushort NUMPAD_2 = 0x50;
    public const ushort NUMPAD_3 = 0x51;
    public const ushort NUMPAD_4 = 0x4B;
    public const ushort NUMPAD_5 = 0x4C;
    public const ushort NUMPAD_6 = 0x4D;
    public const ushort NUMPAD_7 = 0x47;
    public const ushort NUMPAD_8 = 0x48;
    public const ushort NUMPAD_9 = 0x49;
    public const ushort NUMPAD_PLUS = 0x4E;
    public const ushort NUMPAD_MINUS = 0x4A;
    public const ushort NUMPAD_PERIOD = 0x53;
    public const ushort NUMPAD_ENTER = 0x9C;
    public const ushort NUMPAD_BACKSLASH = 0xB5;

    public const ushort LEFT_MOUSE = 0x100;
    public const ushort RIGHT_MOUSE = 0x101;
    public const ushort MIDDLE_MOUSE = 0x102;
    public const ushort MOUSE3 = 0x103;
    public const ushort MOUSE4 = 0x104;
    public const ushort MOUSE5 = 0x105;
    public const ushort MOUSE6 = 0x106;
    public const ushort MOUSE7 = 0x107;
    public const ushort MOUSE_WHEEL_UP = 0x108;
    public const ushort MOUSE_WHEEL_DOWN = 0x109;
}
